services:
  postgres:
    container_name : 'postgres_new'
    image: postgres:latest
    ports:
    - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d new_db" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
    - POSTGRES_DB=new_db
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=*****


  django:
    container_name : 'django_new'
    build: .
    depends_on: 
      postgres: 
        condition: service_healthy
    entrypoint: bash -c "python manage.py makemigrations && python manage.py migrate"


  gunicorn:
    container_name : 'gunicorn-new'
    build: .
    command: gunicorn recipes.wsgi:application -w 4 -b 0.0.0.0:8002
    ports:
    - 8002:8002
    depends_on:
    - django

  nginx:
    container_name : 'nginx-new'
    image: nginx:latest
    depends_on:
    - gunicorn
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
    - "8080:80"
    environment:
    - NGINX_PORT=80
